<a href="https://colab.research.google.com/github/arunsundar2005/Numpy/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.ndim

2

In [ ]:
A.shape

(3, 3)

In [ ]:
A.size

9

In [ ]:
B = A.flatten()


In [ ]:
B


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B.sum()

45

In [ ]:
A.sum()


45

In [ ]:
A.sum(axis = 0)  # Column based Addition

array([12, 15, 18])

In [ ]:
A.sum(axis = 1) # Row based Additon

array([ 6, 15, 24])

In [ ]:
# A.sum(axis = 2)  # som on for higher dimensions

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.linalg.det(A)

0.0

In [ ]:
from numpy import linalg as la

In [ ]:
la.det(A)

0.0

In [ ]:
la.cond(A)

3.813147060626918e+16

In [ ]:
A = np.array(
    [
        [4, -2],
        [1,1]
    ]
)

In [ ]:
la.eig(A)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]]))

In [ ]:
T = np.array(
    [
        [1,0],
        [0,1]
    ]
)

In [ ]:
la.det(T)

1.0

In [ ]:
np.dot(A,T)

array([[ 4, -2],
       [ 1,  1]])

In [ ]:
np.dot(T,A)

array([[ 4, -2],
       [ 1,  1]])

In [ ]:
X = np.array(
    [
        [4,6,10],
        [3,10,13],
        [-2,-6,-8]
    ]
)

In [ ]:
eig_val, eig_vec = la.eig(X)

In [ ]:
eig_val

array([ 4.00000000e+00,  2.00000000e+00, -8.36413379e-16])

In [ ]:
eig_vec

array([[ 0.45749571,  0.40824829, -0.57735027],
       [ 0.76249285, -0.81649658, -0.57735027],
       [-0.45749571,  0.40824829,  0.57735027]])

In [ ]:
X

array([[ 4,  6, 10],
       [ 3, 10, 13],
       [-2, -6, -8]])

In [ ]:
X.swapaxes(0,1) # Same as Transpose??

array([[ 4,  3, -2],
       [ 6, 10, -6],
       [10, 13, -8]])

In [ ]:
X.transpose()

array([[ 4,  3, -2],
       [ 6, 10, -6],
       [10, 13, -8]])

In [ ]:
X.trace()


6